### ISSUE TITLE
Google Colaboratoryでの「9.4.2 ブースティング」の実行エラーにつきまして

### ISSUE THREAD

**Issue by hirokawayuichi** [taroyabuki/fromzero#1]
矢吹先生、辻先生

お忙しいところ、失礼いたします。
09.04.ipynbの件ですが、Google colaboratory上で下記エラーが発生するようになりました。
1年前は問題なく実行できていたのですが、もし解決方法がございましたら、ご教示をいただければ幸いです。

大変お手数ではございますが、何卒よろしくお願いいたします。

・「9.4.2 ブースティング」のセル実行時エラー
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-2-898a9b3d82f5>](https://3w3eopbsnlj-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20230920-060121_RC00_566908972#) in <cell line: 2>()
     10                 'subsample'       : [0.5, 0.75, 1]},
     11     cv=5, # 5分割交差検証
---> 12     n_jobs=1).fit(X, y) # n_jobs=-1ではない．
     13 warnings.simplefilter('default') # これ以降，警告を表示する．
     14 

3 frames
[/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py](https://3w3eopbsnlj-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20230920-060121_RC00_566908972#) in _warn_or_raise_about_fit_failures(results, error_score)
    365                 f"Below are more details about the failures:\n{fit_errors_summary}"
    366             )
--> 367             raise ValueError(all_fits_failed_message)
    368 
    369         else:

ValueError: 
All the 540 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
540 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py", line 1440, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['setosa' 'versicolor' 'virginica']

**Comment by taroyabuki** [comment]
`LabelEncoder`を使ってラベルを数値に変換してください．配布しているコードはそのように修正しました．

**Comment by hirokawayuichi** [comment]
矢吹先生

迅速なご対応をいただき、誠に有難うございます。
お陰様で大変助かりました。
