### ISSUE TITLE
5.1.3 ウェブ上の表につきまして

### ISSUE THREAD

**Issue by hirokawayuichi** [taroyabuki/fromzero#2]
矢吹先生

大変お世話になっております．
「ゼロからはじめるデータサイエンス入門」のGoogle colab用Pythonコード「5.1.3 ウェブ上の表」でcsvファイルを直接読み込むと末尾に記載のエラーが発生しました．
1年前は問題なく実行できていましたが，最近，実行エラーが発生するようになったようです．

試しにcsvをhtml(table)に変換したところ正常に読み込めました．
ご参考のため，zip圧縮したhtmlを添付します．
[exam.zip](https://github.com/taroyabuki/fromzero/files/13334184/exam.zip)

よろしくお願いいたします．

(以下，実行コードとエラー内容です．)

my_url = 'https://github.com/taroyabuki/fromzero/blob/master/data/exam.csv'
my_tables = pd.read_html(my_url)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-20-12dbc6b66a6d>](https://cmknu8es26j-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231109-060126_RC00_580860867#) in <cell line: 2>()
      1 my_url = 'https://github.com/taroyabuki/fromzero/blob/master/data/exam.csv'
----> 2 my_tables = pd.read_html(my_url)

5 frames
[/usr/local/lib/python3.10/dist-packages/pandas/io/html.py](https://cmknu8es26j-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231109-060126_RC00_580860867#) in _parse_tables(self, doc, match, attrs)
    616 
    617         if not tables:
--> 618             raise ValueError("No tables found")
    619 
    620         result = []

ValueError: No tables found

**Comment by taroyabuki** [comment]
ご連絡ありがとうございます．

GitHub上でのCSVファイルの表示方法が変わったようです．

別のファイル https://taroyabuki.github.io/fromzero/exam.html を用意したので，それを使ってください．

公開しているコードは修正しました．

**Comment by hirokawayuichi** [comment]
迅速なご対応をいただき，誠にご有難うございます．
確認をいたしました．
