### ISSUE TITLE
5.2.2 ワンホットエンコーディングにつきまして

### ISSUE THREAD

**Issue by hirokawayuichi** [taroyabuki/fromzero#3]
矢吹先生

度々で申し訳ございません．
「ゼロからはじめるデータサイエンス入門」のGoogle colab用Pythonコード「5.2.2 ワンホットエンコーディング」ですが，末尾の実行エラーが発生しました．

関数get_feature_names()はget_feature_names_out()に名前が変更されたようで関数名を修正すればエラーは出なくなりました．

よろしくお願いいたします．

(以下，実行時エラーです．)

my_names = my_enc.get_feature_names()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-59-85b05709e6d3>](https://cmknu8es26j-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231109-060126_RC00_580860867#) in <cell line: 12>()
     10 tmp = my_enc.fit_transform(
     11     my_df[['class']]).toarray()
---> 12 my_names = my_enc.get_feature_names()
     13 pd.DataFrame(tmp, columns=my_names)
     14 #>    x0_A  x0_B  x0_C

AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'

**Comment by taroyabuki** [comment]
ご連絡ありがとうございます．

公開しているコードを修正しました．

**Comment by hirokawayuichi** [comment]
迅速なご対応をいただき，誠にご有難うございます．
こちらの修正も確認をさせていただきました．

今後とも何卒よろしくお願いいたします．
