### ISSUE TITLE
Google colabでの「10.3.3 決定木の描画」実行エラーにつきまして

### ISSUE THREAD

**Issue by hirokawayuichi** [taroyabuki/fromzero#4]
矢吹先生

大変お世話になっております．

ゼロからはじめるデータサイエンス入門の件ですが，
10-colab.ipynbの「10.3.3 決定木の描画」の実行で下記エラーが発生しました．

1年前は問題なく動作していたのですが，対処法などがございましたらご教示をいただければ幸いです．
大変お手数ではございますが，何卒よろしくお願いいたします．

(以下，Pythonコードとエラーメッセージです．)

my_enc  = my_pipeline.named_steps['ohe']  # パイプラインからエンコーダを取り出す．
my_tree = my_pipeline.named_steps['tree'] # パイプラインから木を取り出す．

my_dot = tree.export_graphviz(
    decision_tree=my_tree,
    out_file=None,
    feature_names=my_enc.get_feature_names(),
    class_names=my_pipeline.classes_,
    filled=True)
graphviz.Source(my_dot)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-171084abff97>](https://localhost:8080/#) in <cell line: 4>()
      5     decision_tree=my_tree,
      6     out_file=None,
----> 7     feature_names=my_enc.get_feature_names(),
      8     class_names=my_pipeline.classes_,
      9     filled=True)

AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'

**Comment by taroyabuki** [comment]
ご報告ありがとうございます。

とりあえずは，
feature_names=my_enc.get_feature_names_out(),
としてください。

後方互換性が大事な場合は，
feature_names=my_enc.get_feature_names_out() if hasattr(my_enc, 'get_feature_names_out') else my_enc.get_feature_names(),
です。

配布するコードは後で修正します。

**Comment by hirokawayuichi** [comment]
休日にご対応をいただき，誠に有難うございます．
お陰様で大変参考になりました．

なお，「10.4 ロジスティック回帰」でも同様のエラーが発生するため，
tmp = my_ohe.get_feature_names()
を
tmp = my_ohe.get_feature_names_out() if hasattr(my_ohe, 'get_feature_names_out') else my_ohe.get_feature_names()
に書き換える必要があるようです．

大変お手数ではございますが，
何卒よろしくお願いいたします．

**Comment by taroyabuki** [comment]
https://github.com/taroyabuki/fromzero/commit/75997e6109a27567437777d1a16bbe5ef4ebab89 で修正しました．

ご報告ありがとうございます．
